"""Curated high-frequency electrical engineering terminology.

Pairs are distilled from common IEC/GB terminology and public engineering usage.
No standard definitions or proprietary explanatory text are reproduced here.
"""


SOURCE = "公开术语整理（IEC Electropedia / GB/T 2900 体系核对）"


ELECTRICAL_TERMS = (
    # Power systems and basic quantities
    ("alternating current", "交流电", "专业术语", "电力系统"),
    ("direct current", "直流电", "专业术语", "电力系统"),
    ("three-phase system", "三相系统", "专业术语", "电力系统"),
    ("single-phase system", "单相系统", "专业术语", "电力系统"),
    ("phase conductor", "相导体", "专业术语", "电力系统"),
    ("neutral conductor", "中性导体", "专业术语", "电力系统"),
    ("protective conductor", "保护导体", "专业术语", "电力系统"),
    ("PEN conductor", "保护接地中性导体", "专业术语", "电力系统"),
    ("line voltage", "线电压", "专业术语", "电力系统"),
    ("phase voltage", "相电压", "专业术语", "电力系统"),
    ("nominal voltage", "标称电压", "专业术语", "电力系统"),
    ("rated frequency", "额定频率", "专业术语", "电力系统"),
    ("voltage deviation", "电压偏差", "专业术语", "电力系统"),
    ("voltage fluctuation", "电压波动", "专业术语", "电力系统"),
    ("voltage drop", "电压降", "专业术语", "电力系统"),
    ("voltage sag", "电压暂降", "专业术语", "电能质量"),
    ("voltage swell", "电压暂升", "专业术语", "电能质量"),
    ("power factor", "功率因数", "专业术语", "电力系统"),
    ("active power", "有功功率", "专业术语", "电力系统"),
    ("reactive power", "无功功率", "专业术语", "电力系统"),
    ("apparent power", "视在功率", "专业术语", "电力系统"),
    ("reactive power compensation", "无功补偿", "专业术语", "电力系统"),
    ("harmonic distortion", "谐波畸变", "专业术语", "电能质量"),
    ("total harmonic distortion", "总谐波畸变率", "专业术语", "电能质量"),
    ("inrush current", "涌流", "专业术语", "电力系统"),
    ("peak current", "峰值电流", "专业术语", "电力系统"),
    ("prospective short-circuit current", "预期短路电流", "专业术语", "电力系统"),
    ("earth fault current", "接地故障电流", "专业术语", "电力系统"),
    ("load current", "负载电流", "专业术语", "电力系统"),
    ("demand factor", "需要系数", "专业术语", "负荷计算"),
    ("diversity factor", "同时系数", "专业术语", "负荷计算"),
    ("load factor", "负荷率", "专业术语", "负荷计算"),
    ("installed capacity", "装机容量", "专业术语", "负荷计算"),
    ("maximum demand", "最大需量", "专业术语", "负荷计算"),
    ("power supply reliability", "供电可靠性", "专业术语", "电力系统"),
    ("power distribution system", "配电系统", "专业术语", "电力系统"),
    ("transmission line", "输电线路", "专业术语", "电力系统"),
    ("distribution line", "配电线路", "专业术语", "电力系统"),
    ("overhead line", "架空线路", "专业术语", "电力系统"),
    ("ring main", "环网", "专业术语", "电力系统"),
    ("radial feeder", "放射式馈线", "专业术语", "电力系统"),
    ("incoming feeder", "进线馈线", "专业术语", "电力系统"),
    ("outgoing feeder", "出线馈线", "专业术语", "电力系统"),
    ("substation", "变电站", "专业术语", "电力系统"),
    ("switching station", "开关站", "专业术语", "电力系统"),

    # Switchgear and protection
    ("air circuit breaker", "空气断路器", "专业术语", "开关与保护"),
    ("vacuum circuit breaker", "真空断路器", "专业术语", "开关与保护"),
    ("moulded case circuit breaker", "塑料外壳式断路器", "专业术语", "开关与保护"),
    ("miniature circuit breaker", "小型断路器", "专业术语", "开关与保护"),
    ("residual current circuit breaker", "剩余电流动作断路器", "专业术语", "开关与保护"),
    ("residual current device", "剩余电流保护器", "专业术语", "开关与保护"),
    ("disconnecting switch", "隔离开关", "专业术语", "开关与保护"),
    ("switch disconnector", "隔离开关", "专业术语", "开关与保护"),
    ("earthing switch", "接地开关", "专业术语", "开关与保护"),
    ("load break switch", "负荷开关", "专业术语", "开关与保护"),
    ("fuse switch", "熔断器式开关", "专业术语", "开关与保护"),
    ("fuse link", "熔断体", "专业术语", "开关与保护"),
    ("contactor", "接触器", "专业术语", "开关与保护"),
    ("thermal overload relay", "热过载继电器", "专业术语", "开关与保护"),
    ("overcurrent protection", "过电流保护", "专业术语", "继电保护"),
    ("short-circuit protection", "短路保护", "专业术语", "继电保护"),
    ("earth fault protection", "接地故障保护", "专业术语", "继电保护"),
    ("differential protection", "差动保护", "专业术语", "继电保护"),
    ("distance protection", "距离保护", "专业术语", "继电保护"),
    ("under-voltage protection", "欠电压保护", "专业术语", "继电保护"),
    ("overvoltage protection", "过电压保护", "专业术语", "继电保护"),
    ("reverse power protection", "逆功率保护", "专业术语", "继电保护"),
    ("breaker failure protection", "断路器失灵保护", "专业术语", "继电保护"),
    ("automatic reclosing", "自动重合闸", "专业术语", "继电保护"),
    ("selective coordination", "选择性配合", "专业术语", "继电保护"),
    ("protection setting", "保护定值", "专业术语", "继电保护"),
    ("tripping characteristic", "脱扣特性", "专业术语", "继电保护"),
    ("instantaneous trip", "瞬时脱扣", "专业术语", "继电保护"),
    ("long-time delay", "长延时", "专业术语", "继电保护"),
    ("short-time delay", "短延时", "专业术语", "继电保护"),
    ("breaking capacity", "分断能力", "专业术语", "开关与保护"),
    ("making capacity", "接通能力", "专业术语", "开关与保护"),
    ("rated short-circuit breaking current", "额定短路开断电流", "专业术语", "开关与保护"),
    ("rated short-time withstand current", "额定短时耐受电流", "专业术语", "开关与保护"),
    ("interlocking", "联锁", "专业术语", "开关与保护"),
    ("mechanical interlock", "机械联锁", "专业术语", "开关与保护"),
    ("electrical interlock", "电气联锁", "专业术语", "开关与保护"),
    ("withdrawable unit", "抽出式单元", "专业术语", "开关与保护"),
    ("bus coupler", "母联", "专业术语", "开关与保护"),

    # Transformers, machines, control
    ("power transformer", "电力变压器", "专业术语", "变压器与电机"),
    ("distribution transformer", "配电变压器", "专业术语", "变压器与电机"),
    ("dry-type transformer", "干式变压器", "专业术语", "变压器与电机"),
    ("oil-immersed transformer", "油浸式变压器", "专业术语", "变压器与电机"),
    ("isolation transformer", "隔离变压器", "专业术语", "变压器与电机"),
    ("instrument transformer", "互感器", "专业术语", "变压器与电机"),
    ("turns ratio", "变比", "专业术语", "变压器与电机"),
    ("vector group", "联结组标号", "专业术语", "变压器与电机"),
    ("tap changer", "分接开关", "专业术语", "变压器与电机"),
    ("on-load tap changer", "有载分接开关", "专业术语", "变压器与电机"),
    ("no-load loss", "空载损耗", "专业术语", "变压器与电机"),
    ("load loss", "负载损耗", "专业术语", "变压器与电机"),
    ("short-circuit impedance", "短路阻抗", "专业术语", "变压器与电机"),
    ("temperature rise", "温升", "专业术语", "变压器与电机"),
    ("insulation class", "绝缘等级", "专业术语", "变压器与电机"),
    ("induction motor", "异步电动机", "专业术语", "变压器与电机"),
    ("synchronous motor", "同步电动机", "专业术语", "变压器与电机"),
    ("variable frequency drive", "变频器", "专业术语", "电机控制"),
    ("soft starter", "软起动器", "专业术语", "电机控制"),
    ("direct-on-line starter", "直接起动器", "专业术语", "电机控制"),
    ("star-delta starter", "星三角起动器", "专业术语", "电机控制"),
    ("motor control centre", "电动机控制中心", "专业术语", "电机控制"),
    ("local control station", "就地控制站", "专业术语", "电机控制"),
    ("remote control", "远方控制", "专业术语", "电机控制"),
    ("emergency stop", "紧急停止", "专业术语", "电机控制"),

    # Cables, earthing, lightning
    ("power cable", "电力电缆", "专业术语", "电缆与接地"),
    ("control cable", "控制电缆", "专业术语", "电缆与接地"),
    ("instrumentation cable", "仪表电缆", "专业术语", "电缆与接地"),
    ("fire-resistant cable", "耐火电缆", "专业术语", "电缆与接地"),
    ("flame-retardant cable", "阻燃电缆", "专业术语", "电缆与接地"),
    ("low-smoke zero-halogen cable", "低烟无卤电缆", "专业术语", "电缆与接地"),
    ("cross-linked polyethylene", "交联聚乙烯", "专业术语", "电缆与接地"),
    ("cable tray", "电缆桥架", "专业术语", "电缆与接地"),
    ("cable ladder", "梯式电缆桥架", "专业术语", "电缆与接地"),
    ("cable trench", "电缆沟", "专业术语", "电缆与接地"),
    ("cable termination", "电缆终端", "专业术语", "电缆与接地"),
    ("cable joint", "电缆接头", "专业术语", "电缆与接地"),
    ("minimum bending radius", "最小弯曲半径", "专业术语", "电缆与接地"),
    ("current-carrying capacity", "载流量", "专业术语", "电缆与接地"),
    ("derating factor", "降额系数", "专业术语", "电缆与接地"),
    ("earthing electrode", "接地极", "专业术语", "电缆与接地"),
    ("earthing conductor", "接地导体", "专业术语", "电缆与接地"),
    ("main earthing terminal", "总接地端子", "专业术语", "电缆与接地"),
    ("equipotential bonding", "等电位联结", "专业术语", "电缆与接地"),
    ("earth resistance", "接地电阻", "专业术语", "电缆与接地"),
    ("touch voltage", "接触电压", "专业术语", "电缆与接地"),
    ("step voltage", "跨步电压", "专业术语", "电缆与接地"),
    ("lightning protection system", "防雷装置", "专业术语", "防雷"),
    ("air-termination system", "接闪系统", "专业术语", "防雷"),
    ("down conductor", "引下线", "专业术语", "防雷"),
    ("surge protective device", "浪涌保护器", "专业术语", "防雷"),

    # Building services, drawings, testing
    ("main distribution board", "主配电板", "专业术语", "建筑电气"),
    ("final distribution board", "终端配电箱", "专业术语", "建筑电气"),
    ("consumer unit", "用户配电箱", "专业术语", "建筑电气"),
    ("emergency power supply", "应急电源", "专业术语", "建筑电气"),
    ("uninterruptible power supply", "不间断电源", "专业术语", "建筑电气"),
    ("diesel generator set", "柴油发电机组", "专业术语", "建筑电气"),
    ("automatic transfer switch", "自动转换开关", "专业术语", "建筑电气"),
    ("emergency lighting", "应急照明", "专业术语", "建筑电气"),
    ("maintained emergency lighting", "持续型应急照明", "专业术语", "建筑电气"),
    ("illuminance", "照度", "专业术语", "照明"),
    ("luminous flux", "光通量", "专业术语", "照明"),
    ("colour temperature", "色温", "专业术语", "照明"),
    ("degree of protection", "防护等级", "专业术语", "建筑电气"),
    ("single-line diagram", "单线图", "专业术语", "图纸与CAD"),
    ("schematic diagram", "原理图", "专业术语", "图纸与CAD"),
    ("wiring diagram", "接线图", "专业术语", "图纸与CAD"),
    ("terminal diagram", "端子图", "专业术语", "图纸与CAD"),
    ("cable schedule", "电缆清册", "专业术语", "图纸与CAD"),
    ("load schedule", "负荷表", "专业术语", "图纸与CAD"),
    ("equipment layout", "设备布置图", "专业术语", "图纸与CAD"),
    ("as-built drawing", "竣工图", "专业术语", "图纸与CAD"),
    ("insulation resistance test", "绝缘电阻试验", "专业术语", "试验与调试"),
    ("dielectric withstand test", "介电强度试验", "专业术语", "试验与调试"),
    ("continuity test", "导通试验", "专业术语", "试验与调试"),
    ("primary injection test", "一次注流试验", "专业术语", "试验与调试"),
    ("secondary injection test", "二次注流试验", "专业术语", "试验与调试"),
    ("factory acceptance test", "工厂验收试验", "专业术语", "试验与调试"),
    ("site acceptance test", "现场验收试验", "专业术语", "试验与调试"),
    ("commissioning test", "调试试验", "专业术语", "试验与调试"),
    ("test certificate", "试验证书", "专业术语", "试验与调试"),

    # Engineering and specification phrases
    ("shall comply with", "应符合", "固定短语", "工程表达"),
    ("shall be suitable for", "应适用于", "固定短语", "工程表达"),
    ("shall be capable of", "应能", "固定短语", "工程表达"),
    ("shall be equipped with", "应配备", "固定短语", "工程表达"),
    ("shall be installed in accordance with", "应按照……安装", "固定短语", "工程表达"),
    ("subject to approval", "须经批准", "固定短语", "工程表达"),
    ("unless otherwise indicated", "除非另有标示", "固定短语", "工程表达"),
    ("as shown on the drawings", "如图所示", "固定短语", "工程表达"),
    ("complete with all accessories", "配齐所有附件", "固定短语", "工程表达"),
    ("ready for operation", "具备投运条件", "固定短语", "工程表达"),
    ("normal service conditions", "正常使用条件", "固定短语", "工程表达"),
    ("ambient temperature", "环境温度", "专业术语", "工程表达"),
    ("relative humidity", "相对湿度", "专业术语", "工程表达"),
    ("altitude above sea level", "海拔高度", "专业术语", "工程表达"),
)
